#' Make fake point data
#'
#' This function generates fake point data to be used for testing functions, or
#' for making reproducible examples. For each `fcst_dttm` and `SID` a time
#' series of forecasts is produced using a random walk. Observations are
#' generated by adding small random numbers to the forecast values. For ensemble
#' data, each member is generated by adding small random perturbations to the
#' first generated forecast.
#'
#' @param fcst_dttm A vector of date-times, for example as produced by
#'   \code{\link[harpCore]{seq_dttm}}.
#' @param fcst_model A vector of forecast model names.
#' @param lead_time A vector of lead times.
#' @param SID A vector of station IDs.
#' @param members Either `NULL` (the default) to generate deterministic data,
#'   or a numeric vector of member numbers to generate ensemble data.
#' @param seed A seed to generate random numbers. By setting this to a numeric
#'   value, the generated data are fully reproducible.
#'
#' @return A `harp_point_df` data frame or a `harp_list`.
#' @export
#'
#' @examples
#' # Generate deterministic data for 2 stations for 1 model
#' fake_point_data(20240901, "a", lead_time = seq(0, 3), SID = c(1, 2))
#'
#' # Do the same but for 3 models
#' fake_point_data(20240901, letters[1:3], lead_time = seq(0, 3), SID = c(1, 2))
#'
#' # Generate ensemble data for 4 members + control
#' fake_point_data(
#'   20240901, "a", lead_time = seq(0, 3), SID = c(1, 2), members = seq(0, 4)
#' )
#'
fake_point_data <- function(
  fcst_dttm,
  fcst_model,
  lead_time = seq(0, 48),
  SID       = seq(1000, 1100),
  members   = NULL,
  seed      = NULL
) {

  if (is.null(members)) {
    return(fake_det_data(fcst_dttm, fcst_model, lead_time, SID, seed))
  }
  fake_eps_data(fcst_dttm, fcst_model, lead_time, SID, members, seed)
}

fake_det_data <- function(
  fcst_dttm,
  fcst_model,
  lead_time = seq(0, 48),
  SID       = seq(1000, 1100),
  seed      = NULL
) {

  fcst_data <- tibble::tibble(
    fcst_dttm = harpCore::as_dttm(fcst_dttm),
    SID       = rep(list(SID), length(fcst_dttm)),
  )

  fcst_data <- tidyr::unnest(fcst_data, "SID")

  fcst <-  lapply(
    seq_len(nrow(fcst_data)),
    function(x) {
      if (!is.null(seed)) {
        set.seed(seed + x)
      }
      cumsum(rnorm(length(lead_time), sd = 0.25))
    }
  )

  fcst_data <- dplyr::mutate(
    fcst_data,
    lead_time = rep(list(lead_time), nrow(fcst_data)),
    fcst      = fcst
  )

  fcst_data <- tidyr::unnest(
    fcst_data, dplyr::all_of(c("lead_time", "fcst"))
  )
  fcst_data$valid_dttm <- fcst_data$fcst_dttm +
    harpCore::to_seconds(fcst_data$lead_time)

  set.seed(seed)
  fcst_data$obs <- fcst_data$fcst + rnorm(nrow(fcst_data), sd = 0.25)

  if (length(fcst_model) == 1) {
    colnames(fcst_data)[colnames(fcst_data) == "fcst"] <- paste0(
      fcst_model, "_det"
    )
    return(
      harpCore::as_harp_df(
        fcst_data[c(
          "fcst_dttm", "lead_time",
          "valid_dttm", "SID", paste0(fcst_model, "_det"), "obs"
        )]
      )
    )
  }

  out <- mapply(
    function(x, y) {
      if (!is.null(seed)) {
        set.seed(seed + y)
      }
      res <- dplyr::mutate(
        fcst_data, fcst = .data$fcst + rnorm(nrow(fcst_data), sd = 0.1)
      )
      colnames(res)[colnames(res) == "fcst"] <- paste0(x, "_det")
      harpCore::as_harp_df(
        res[c(
          "fcst_dttm", "lead_time",
          "valid_dttm", "SID", paste0(x, "_det"), "obs"
        )])
    },
    fcst_model, seq_along(fcst_model),
    SIMPLIFY = FALSE
  )
  names(out) <- fcst_model
  harpCore::as_harp_list(out)
}

fake_eps_data <- function(
  fcst_dttm,
  fcst_model,
  lead_time = seq(0, 48),
  SID       = seq(1000, 1100),
  members   = seq(0, 6),
  seed      = NULL
) {

  out <- fake_det_data(fcst_dttm, fcst_model, lead_time, SID, seed)

  members <- paste0(
    "_mbr", formatC(members[2:length(members)], width = 3, flag = "0")
  )

  if (!harpCore::is_harp_list(out)) {
    colnames(out)[colnames(out) == "fcst"] <- paste0(fcst_model, "_mbr000")
    count <- 0
    for (member in members) {
      if (!is.null(seed)) {
        set.seed(seed + count)
      }
      out[[paste0(fcst_model, member)]] <-
        out[[paste0(fcst_model, "_mbr000")]] + rnorm(nrow(out), sd = 0.1)
      count <- count + 1
    }
    return(
      harpCore::as_harp_df(
        out[c(grep("obs", colnames(out), invert = TRUE, value = TRUE), "obs")]
      )
    )
  }

  harpCore::as_harp_list(mapply(
    function(x, y, z) {
      colnames(x)[colnames(x) == "fcst"] <- paste0(y, "_mbr000")
      count <- 0
      for (member in members) {
        if (!is.null(seed)) {
          set.seed(seed + z + count)
        }
        x[[paste0(y, member)]] <-
          x[[paste0(y, "_mbr000")]] + rnorm(nrow(x), sd = 0.1)
        count <- count + 1
      }
      harpCore::as_harp_df(
          x[c(grep("obs", colnames(x), invert = TRUE, value = TRUE), "obs")]
      )
    },
    out,
    fcst_model,
    seq_along(fcst_model),
    SIMPLIFY = FALSE
  ))

}
