# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sort a 2d array.
#'
#' @param x A two dimensional numeric array.
#' @param byrow Set to true sort rows, false to sort columns.
#' @export
sort_members <- function(x, byrow = TRUE) {
    .Call('_harpPoint_sort_members', PACKAGE = 'harpPoint', x, byrow)
}

#' Compute the rank histogram for an EPS
#'
#' @param obs A vector of observations.
#' @param fc A two dimensional array of EPS data with members in columns.
#' @export
rankHistogram <- function(obs, fc) {
    .Call('_harpPoint_rankHistogram', PACKAGE = 'harpPoint', obs, fc)
}

#' Compute the forecast probabilities for given thresholds
#'
#' @param fc A two dimensional array of EPS data with members in columns.
#' @param byrow The thresholds to compute probabilities for
#' @export
fcprob <- function(fc, thresholds) {
    .Call('_harpPoint_fcprob', PACKAGE = 'harpPoint', fc, thresholds)
}

