# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute economic value score
#'
#' @param obs A vector observations (value 0,1)
#' @param pred A vector of probabilities [0,1].
#' @param costloss A vector of cost/loss ratios
#' @param thresholds A vector of threshold probabilities
#' @return a list of cl, value, Vmax, Venv, H, F, s, n
ecoval <- function(obs, pred, costloss, thresholds) {
    .Call('_harpPoint_ecoval', PACKAGE = 'harpPoint', obs, pred, costloss, thresholds)
}

#' Sort a 2d array.
#'
#' @param x A two dimensional numeric array.
#' @param byrow Set to true sort rows, false to sort columns.
sort_members <- function(x, byrow = TRUE) {
    .Call('_harpPoint_sort_members', PACKAGE = 'harpPoint', x, byrow)
}

#' Sort a 2d array from a data frame.
#'
#' @param x A two dimensional numeric array.
#' @param byrow Set to true sort rows, false to sort columns.
sort_members_df <- function(df, byrow = TRUE) {
    .Call('_harpPoint_sort_members_df', PACKAGE = 'harpPoint', df, byrow)
}

#' Compute the rank histogram for an EPS
#'
#' @param obs A vector of observations.
#' @param fc A two dimensional array of EPS data with members in columns.
rankHistogram <- function(obs, df) {
    .Call('_harpPoint_rankHistogram', PACKAGE = 'harpPoint', obs, df)
}

#' Compute the forecast probabilities for given thresholds
#'
#' @param fc A two dimensional array of EPS data with members in columns.
#' @param byrow The thresholds to compute probabilities for
fcprob <- function(fc, thresholds, comparator = "ge", includeLow = TRUE, includeHigh = TRUE) {
    .Call('_harpPoint_fcprob', PACKAGE = 'harpPoint', fc, thresholds, comparator, includeLow, includeHigh)
}

#' Compute ROC and area under ROC
#'
#' @param obs A vector observations (value 0,1)
#' @param pred A vector of probabilities [0,1].
#' @param thresholds A vector of threshold probabilities
#' @return a list with area and vectors thresholds, H, F
roc <- function(obs, pred, thresholds) {
    .Call('_harpPoint_roc', PACKAGE = 'harpPoint', obs, pred, thresholds)
}

